// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';

export function AddBackupRecord(arg1:string,arg2:string):Promise<void>;

export function GetBackupHistory():Promise<Array<main.BackupRecord>>;

export function GetFileMetadata(arg1:Array<string>):Promise<Array<main.FileInfo>>;

export function ListBackupContents(arg1:string,arg2:string):Promise<Array<core.FileMetadata>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFiles(arg1:boolean):Promise<Array<string>>;

export function StartBackup(arg1:main.BackupConfig):Promise<string>;

export function StartRestore(arg1:main.RestoreConfig):Promise<string>;

export function StopOperation():Promise<void>;
