// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartBackup(arg1) {
  return window['go']['main']['App']['StartBackup'](arg1);
}

export function StartRestore(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartRestore'](arg1, arg2, arg3);
}
