// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function StartBackup(arg1:main.BackupConfig):Promise<string>;

export function StartRestore(arg1:string,arg2:string,arg3:string):Promise<string>;
