// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {core} from '../models';

export function AddBackupRecord(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function CreateProfile(arg1:string,arg2:Array<string>):Promise<main.Profile>;

export function CreateTask(arg1:core.BackupTask):Promise<core.BackupTask>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetBackupHistory():Promise<Array<main.BackupRecord>>;

export function GetFileMetadata(arg1:Array<string>):Promise<Array<main.FileInfo>>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function GetTasks():Promise<Array<core.BackupTask>>;

export function ListDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string):Promise<void>;

export function RunTaskNow(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFiles(arg1:boolean):Promise<Array<string>>;

export function StartBackup(arg1:main.BackupConfig):Promise<string>;

export function StartRestore(arg1:main.RestoreConfig):Promise<string>;

export function StopOperation():Promise<void>;

export function UpdateTask(arg1:core.BackupTask):Promise<void>;
