// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBackupRecord(arg1, arg2) {
  return window['go']['main']['App']['AddBackupRecord'](arg1, arg2);
}

export function GetBackupHistory() {
  return window['go']['main']['App']['GetBackupHistory']();
}

export function GetFileMetadata(arg1) {
  return window['go']['main']['App']['GetFileMetadata'](arg1);
}

export function ListBackupContents(arg1, arg2) {
  return window['go']['main']['App']['ListBackupContents'](arg1, arg2);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles(arg1) {
  return window['go']['main']['App']['SelectFiles'](arg1);
}

export function StartBackup(arg1) {
  return window['go']['main']['App']['StartBackup'](arg1);
}

export function StartRestore(arg1) {
  return window['go']['main']['App']['StartRestore'](arg1);
}

export function StopOperation() {
  return window['go']['main']['App']['StopOperation']();
}
