# .github/workflows/release.yml

name: Release Wails App

# 触发器：当一个以 'v' 开头的 tag 被推送到仓库时触发
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    # 使用策略矩阵 (strategy matrix) 为多个平台并行构建
    strategy:
      matrix:
        # 定义不同操作系统的构建配置
        include:
          - os: ubuntu-latest
            platform: linux
            arch: amd64
            asset_name_suffix: linux-amd64
          - os: windows-latest
            platform: windows
            arch: amd64
            asset_name_suffix: windows-amd64.exe
          - os: macos-latest
            platform: darwin
            arch: universal
            asset_name_suffix: darwin-universal.zip

    # 指定运行器 (runner)
    runs-on: ${{ matrix.os }}

    # 关键改动(1): 为所有 `run` 命令设置默认工作目录
    defaults:
      run:
        working-directory: ./go-backup-app

    steps:
      # 1. 检出整个仓库的代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # 根据你的项目选择合适的 Go 版本

      # 3. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 根据你的项目选择合适的 Node 版本
          # 注意: 缓存路径需要相对于仓库根目录
          cache-dependency-path: go-backup-app/frontend/package-lock.json # 或 yarn.lock

      # 4. (仅 Linux) 安装 CGO 依赖
      # 这个步骤是系统级别的，不需要在子目录运行，所以不受 `defaults` 影响
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      # 5. 安装 Wails CLI (全局安装，不受工作目录影响)
      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # 6. 安装前端依赖
      # 由于设置了 `defaults.run.working-directory`，此命令会在 go-backup-app/ 目录下执行
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # 7. 从 wails.json 中提取项目名称并设置环境变量
      # 此命令会在 go-backup-app/ 目录下执行，能正确找到 wails.json
      - name: Set Environment Variables
        run: |
          PROJECT_NAME=$(jq -r .name wails.json)
          echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV
          
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
          echo "ASSET_NAME=${PROJECT_NAME}-${VERSION}-${{ matrix.asset_name_suffix }}" >> $GITHUB_ENV
          # BINARY_PATH 仍然是相对于工作目录 (go-backup-app) 的
          echo "BINARY_PATH=build/bin/${PROJECT_NAME}" >> $GITHUB_ENV

      # 8. 构建 Wails 应用
      # 此命令会在 go-backup-app/ 目录下执行
      - name: Build Wails Application
        run: wails build -platform ${{ matrix.platform }} -arch ${{ matrix.arch }} -ldflags="-s -w"

      # 9. 打包资源文件
      # 此命令会在 go-backup-app/ 目录下执行，并在此目录下生成最终的产物
      - name: Package Asset
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            zip -r "${{ env.ASSET_NAME }}" "build/bin/"*.app
          else
            mv "${{ env.BINARY_PATH}}$( [ "${{ matrix.os }}" == "windows-latest" ] && echo ".exe" )" "${{ env.ASSET_NAME }}"
          fi

      # 10. 创建 Release 并上传构建产物
      - name: Create Release and Upload Asset
        uses: ncipollo/release-action@v1
        with:
          # 关键改动(2): artifacts 的路径需要包含子目录
          artifacts: "go-backup-app/${{ env.ASSET_NAME }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          allowUpdates: true