# .github/workflows/release.yml

name: Release Wails App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: amd64
            asset_name_suffix: linux-amd64
          - os: windows-latest
            platform: windows
            arch: amd64
            asset_name_suffix: windows-amd64.exe
          - os: macos-latest
            platform: darwin
            arch: universal
            asset_name_suffix: darwin-universal.zip

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./go-backup-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          # =========================================================
          # 关键修复: 明确告诉 setup-go 去哪里找 go.sum 文件以正确设置缓存
          # =========================================================
          cache-dependency-path: go-backup-app/go.sum

      # 3. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache-dependency-path: go-backup-app/frontend/package-lock.json

      # 4. (仅 Linux) 安装 CGO 依赖
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      # 5. 安装 Wails CLI
      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      # 6. 安装前端依赖
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # 7. 从 wails.json 中提取项目名称并设置环境变量
      - name: Set Environment Variables
        run: |
          PROJECT_NAME=$(jq -r .name wails.json)
          echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV
          
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
          echo "ASSET_NAME=${PROJECT_NAME}-${VERSION}-${{ matrix.asset_name_suffix }}" >> $GITHUB_ENV
          echo "BINARY_PATH=build/bin/${PROJECT_NAME}" >> $GITHUB_ENV

      # 8. 构建 Wails 应用
      - name: Build Wails Application
        run: wails build -platform ${{ matrix.platform }} -arch ${{ matrix.arch }} -ldflags="-s -w"

      # 9. 打包资源文件
      - name: Package Asset
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            zip -r "${{ env.ASSET_NAME }}" "build/bin/"*.app
          else
            mv "${{ env.BINARY_PATH}}$( [ "${{ matrix.os }}" == "windows-latest" ] && echo ".exe" )" "${{ env.ASSET_NAME }}"
          fi

      # 10. 创建 Release 并上传构建产物
      - name: Create Release and Upload Asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: "go-backup-app/${{ env.ASSET_NAME }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          allowUpdates: true